import type { MetadataRoute } from "next";

// Required with output: "export" — the manifest is emitted at build time
// rather than served dynamically.
export const dynamic = "force-static";

/**
 * PWA manifest — lets the site be installed to a phone home screen and run
 * without browser chrome. Generated by Next so it lands in the static export.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Golden Era Astro",
    short_name: "Golden Era",
    description:
      "Vedic astrology: kundli, 20 divisional charts, dashas, AI astrologer and live consultations.",
    start_url: "/",
    display: "standalone",
    background_color: "#fff7ed",
    theme_color: "#c1121f",
    orientation: "portrait-primary",
    icons: [
      { src: "/icon.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/apple-icon.png", sizes: "180x180", type: "image/png" },
    ],
  };
}
